import './main.css';
import './main.js';

import exo1 from './exercises/exo1';
import exo2 from './exercises/exo2';
import exo3 from './exercises/exo3';
import exo4 from './exercises/exo4';
import exo5 from './exercises/exo5';
import exo6 from './exercises/exo6';
import exo7 from './exercises/exo7';
import exo8 from './exercises/exo8';
import exo9 from './exercises/exo9';
import exo10 from './exercises/exo10';
import exo11 from './exercises/exo11';
import exo12 from './exercises/exo12';
import exo13 from './exercises/exo13';
import exo14 from './exercises/exo14';

exo1();
exo2();
exo3();
exo4();
exo5();
exo6();
exo7();
exo8();
exo9();
exo10();
exo11();
exo12();
exo13();
exo14();
